/*
 * ConnectDialog.java
 *
 * Created on October 19, 2004, 9:10 PM
 */

package guisanboot.ui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;
import mylib.tool.*;
import guisanboot.res.*;

/**
 *
 * @author  Administrator
 */
public class ConnectDialog_1 extends javax.swing.JDialog {
    Object[] values = null;
    
    /** Creates new form ConnectDialog */
    public ConnectDialog_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public ConnectDialog_1(Frame frame, String ip, int port, String user, String passwd) {
        this(frame,true);
        myInit((SanBootView)frame,ip,port,user,passwd);
    }
    
    public ConnectDialog_1(Frame frame,String ip,int port,String user ){
        this( frame,true );
        myInit( (SanBootView)frame,ip,port,user,"" );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="生成的代码">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Login"));
        jLabel1.setText("Server : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLabel1, gridBagConstraints);

        jTextField1.setPreferredSize(new java.awt.Dimension(120, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        jPanel1.add(jTextField1, gridBagConstraints);

        jLabel2.setText("Port : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jTextField2.setPreferredSize(new java.awt.Dimension(70, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        jPanel1.add(jTextField2, gridBagConstraints);

        jLabel3.setText("User : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jTextField3.setPreferredSize(new java.awt.Dimension(65, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
        jPanel1.add(jTextField3, gridBagConstraints);

        jLabel4.setText("Password : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jPasswordField1.setPreferredSize(new java.awt.Dimension(180, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
        jPanel1.add(jPasswordField1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 1, 1, 1)));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        jPanel3.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        jButton1.setText("Connect");
        jButton1.setPreferredSize(new java.awt.Dimension(81, 24));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.setPreferredSize(new java.awt.Dimension(81, 24));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton2);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        values = null;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ip = jTextField1.getText().trim();
        if( ip.equals("") ){
            JOptionPane.showMessageDialog(this,
                SanBootView.res.getString("ConnectDialog.error.noneIP")
            );
            return;
        }
        
        if( !Check.ipCheck( ip ) ){
            JOptionPane.showMessageDialog(this,
                SanBootView.res.getString("ConnectDialog.error.badIP")
            );
            return;
        }
        
        String _port = jTextField2.getText().trim();
        if( _port.equals("") ){
            JOptionPane.showMessageDialog(this,
                SanBootView.res.getString("ConnectDialog.errMsg.nullPort")
            );
            return;
        }
        
        if( !Check.digitCheck( _port ) ){
            JOptionPane.showMessageDialog(this,
                SanBootView.res.getString("ConnectDialog.errMsg.badPort")
            );
            return;
        }

        int port = ResourceCenter.C_S_PORT;
        try{
            port = Integer.parseInt( _port );
        }catch(Exception ex){}

        if( port <1 || port >65535 ){
            JOptionPane.showMessageDialog(this,
                SanBootView.res.getString("ConnectDialog.errMsg.invalidPort")
            );
            return ;
        }        
        
        String user = jTextField3.getText().trim();
        if( user.equals("") ){
            JOptionPane.showMessageDialog(this,
                SanBootView.res.getString("ConnectDialog.errMsg.noneUser")
            );
            return;
        }
        
        if( Check.checkInput( user ) ){
             JOptionPane.showMessageDialog(null,
                SanBootView.res.getString("ConnectDialog.errMsg.badUser")
             );
             return;
        }
        
        if( user.getBytes().length >= 32 ){
            JOptionPane.showMessageDialog(this,
                SanBootView.res.getString("ConnectDialog.errMsg.invalidUser")
            );
            return;
        }
        
        String pwd = new String( jPasswordField1.getPassword() );
        if( !pwd.equals("") ){    
            if( pwd.getBytes().length >= 32  ){
                JOptionPane.showMessageDialog(this,
                    SanBootView.res.getString("ConnectDialog.errMsg.invalidPwd")
                );
                return;
            }
        }
        
        values = new Object[4];
        values[0] = new String( ip );
        values[1] = new String( user );
        values[2] = new String ( pwd );
        values[3] = new Integer( port );
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ConnectDialog(new javax.swing.JFrame(), true).setVisible( true );
    }
    
    // 变量声明 - 不进行修改//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // 变量声明结束//GEN-END:variables
    
    SanBootView syncView;
    
    private void myInit(SanBootView view,String ip,int port,String user,String passwd){
        syncView = view;
        
        this.jTextField1.setText(ip);
        this.jTextField2.setText(port+"");
        this.jTextField3.setText(user);
        this.jPasswordField1.setText(passwd);
        
        regKeyboardAction();
        jPasswordField1.requestFocus();
        setupLanguage();
        
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter(){
            public void keyPressed( KeyEvent e ){
                if( e.getKeyCode() == KeyEvent.VK_ENTER ){
                    jButton1ActionPerformed(null);
                }
            }
        });         
    }
    
    private void regKeyboardAction(){            
        jTextField1.registerKeyboardAction(
            new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    jTextField2.requestFocusInWindow();
                }
            },
            KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0,true),
            JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
        );
        
        jTextField2.registerKeyboardAction(
            new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    jTextField3.requestFocus();
                }
            },
            KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0,true),
            //JComponent.WHEN_IN_FOCUSED_WINDOW
            JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
        );
          
        jTextField3.registerKeyboardAction(
            new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    jPasswordField1.requestFocus();
                }
            },
            KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0,true),
            //JComponent.WHEN_IN_FOCUSED_WINDOW
            JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
        );
    }
     
    private void setupLanguage(){
        setTitle(SanBootView.res.getString("ConnectDialog.dialog_title"));
        TitledBorder bor = (TitledBorder)jPanel1.getBorder();
        bor.setTitle(SanBootView.res.getString("ConnectDialog.border.title2"));
        jLabel3.setText(SanBootView.res.getString("ConnectDialog.label.text2")); //"Password");
        jLabel2.setText(SanBootView.res.getString("ConnectDialog.label.text4")); //"User");
        jLabel1.setText(SanBootView.res.getString("ConnectDialog.label.text3")); //"Server");
        jLabel4.setText(SanBootView.res.getString("ConnectDialog.label.text1")); //"Port"
        
        jButton1.setText(SanBootView.res.getString("ConnectDialog.button.connect"));
        jButton2.setText(SanBootView.res.getString("common.button.cancel"));
    }
    
    public Object[] getValues(){
        return values;
    }
}
